version: "3"
services:
  redisdb:
    image: redis:latest
    command: redis-server --appendonly yes --maxmemory 8gb --maxclients 1048576
    container_name: requestrepo_redisdb
    restart: always
    volumes:
      - redis_data:/data
  backend:
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN:-requestrepo.com}
    container_name: requestrepo_backend
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - REDIS_HOST=requestrepo_redisdb
    depends_on:
      - redisdb
    volumes:
      - pages_data:/app/pages
      - backend_cert:/app/cert
  dns:
    build:
      context: ./
      dockerfile: ./dns/Dockerfile
    container_name: requestrepo_dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    env_file:
      - .env
    environment:
      - REDIS_HOST=requestrepo_redisdb
    depends_on:
      - redisdb
volumes:
  redis_data:
  pages_data:
  backend_cert:
